version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
    container_name: rabbitmq
  
  redis:
    image: redis:alpine  # Using Redis Alpine for lightweight
    container_name: redis
    ports:
      - "6379:6379"  # Exposing Redis on the default port
    volumes:
      - redis-data:/data  # Redis persistent data

volumes:
  redis-data:  # Named volume for Redis data persistence
